[build]
  publish = "."
  command = ""

# Дозволяємо доступ до success.html напряму
[[redirects]]
  from = "/success.html"
  to = "/success.html"
  status = 200

# Усі інші шляхи → index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200




